version: "3.7"
services:
  prometheus:
    image: prom/prometheus:v2.38.0
    ports:
      - "9090:9090"
    volumes:
      - "./etc:/etc/prometheus"
      - "./data:/prometheus"
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"

  pushgateway:
    image: prom/pushgateway:v1.4.3
    ports:
      - "9091:9091"
